---
title: "Comparison between TIS and IG Gradientu - ceiling/floor issue"
author: "Veru a Jirka Balounovi"
date: "Compiled on: **2026-03-09**  <br> Last updated **`r format(Sys.time(), '%Y-%m-%d')`**"
output:
  html_document:
    code_folding: hide
    df_print: paged
    theme: yeti
    highlight: tango
    toc: yes
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
  pdf_document:
    fig_caption: yes
    toc: yes
editor_options:
  markdown:
    wrap: 72
---

```{=html}
<style type="text/css">
.title {
  text-align: center;
}
.author {
  font-size: 30px;
  text-align: center;
  font-style: italic;
  font-weight: 300;
}
.date {
  font-weight: 300;
}
h1, h2, h3, h4 {
    font-weight: 600;
    margin-top: 2em;
}
body {text-align: justify}
blockquote {
    padding: 10px 20px;
    margin: 0 0 20px;
    font-size: 14px;
    border-left: 5px solid #eee;
}
p {
  text-indent: 2rem;
}
table {
    width:100%;
}
.main-container {
  max-width: 100% !important;
  margin: auto;
}
img{
    height: 100%;
    width: 100%;
    object-fit: cover;
}
.boxBorder {
     border: 2px solid #990066;
     padding: 10px;
     outline: #990066 solid 5px;
     outline-offset: 5px;
   }
</style>
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

if (!require("pacman")) install.packages("pacman")

pacman::p_load(
  tidyverse, purrr, conflicted, renv,
  rio, janitor, GGally, corrplot, sjPlot,
  ggpubr, lme4, lmerTest, performance,
  broom.mixed, patchwork, future, furrr,
  openxlsx, knitr, kableExtra, sessioninfo
)

conflicted::conflicts_prefer(
  dplyr::filter,
  dplyr::mutate,
  dplyr::rename,
  dplyr::summarize,
  dplyr::summarise,
  dplyr::select,
  dplyr::lag,
  purrr::map,
  tidyr::extract,
  janitor::clean_names
)

input_path <- knitr::current_input()
if (nzchar(input_path)) {
  this_dir <- dirname(normalizePath(input_path))
} else {
  this_dir <- getwd()
}

project_root <- normalizePath(file.path(this_dir, "..", ".."))
setwd(project_root)

options(
  myo_pacman_update = FALSE,
  myo_pacman_install = FALSE,
  myo_ncores = 4L,
  myo_run_renv_status = FALSE,
  myo_ceil_flo_data_path_01 = "R:/MYOZITIDY_VýZKUM/_IMMET-GRANT/IMMET štatistika/Data/Raw/Geneactiv/20260302_GGIR_klinika/260302_data_geneactive_clinics.xlsx"
)

source("scripts/functions/FUN_ceil_flo_01.R", local = TRUE)
source("scripts/functions/OBJ_ceil_flo_01.R", local = TRUE)

sel_dep_var_ceil_01 <- c("mmt8", "mmt10", "fi2", "fi3", "haq")
sel_indep_var_ceil_01 <- c("ig_gradient_enmo")
output_root_ceil_01 <- file.path("output", "ceil_flo")
output_fig_dir_ceil_01 <- file.path(output_root_ceil_01, "figures")
output_tab_dir_ceil_01 <- file.path(output_root_ceil_01, "tables")

dir.create(output_fig_dir_ceil_01, showWarnings = FALSE, recursive = TRUE)
dir.create(output_tab_dir_ceil_01, showWarnings = FALSE, recursive = TRUE)

exam_levels_ref_01 <- c("M0", "M3", "M6", "M18", "M30", "M48")

normalize_exam_factor_01 <- function(x, levels_ref = exam_levels_ref_01) {
  x_chr <- stringr::str_to_upper(stringr::str_trim(as.character(x)))
  x_num <- suppressWarnings(readr::parse_number(x_chr))
  x_lab <- dplyr::if_else(is.na(x_num), x_chr, paste0("M", as.integer(x_num)))
  factor(x_lab, levels = levels_ref)
}

d18_ggir_data <- d18_ggir_data |>
  dplyr::mutate(exam = normalize_exam_factor_01(exam)) |>
  droplevels()
```
# Description and Aims


# EDA


# Session info

<details>

<summary>Platform</summary>

```{r session_info_1}
if (!"tidyverse" %in% .packages()) library(tidyverse)
if (!"knitr" %in% .packages()) library(knitr)
if (!"kableExtra" %in% .packages()) library(kableExtra)

df_session_platform <- devtools::session_info()$platform %>%
  unlist(.) %>%
  as.data.frame(.) %>%
  rownames_to_column(.)

colnames(df_session_platform) <- c("Setting", "Value")

kable(
  df_session_platform,
  booktabs = TRUE,
  align = "l",
  caption = "(ref:Reproducibility-SessionInfo-R-environment-title)",
  caption.short = " "
) %>%
  kableExtra::kable_styling(
    full_width = FALSE,
    latex_options = c("hold_position"),
    bootstrap_options = c("striped", "hover", "condensed", "responsive")
  )
```

</details>

<details>

<summary>Used packages</summary>

```{r session_info_2}
session_pkgs <- sessioninfo::package_info() |>
  tibble() |>
  subset(attached == TRUE, select = c(package, loadedversion, date))

knitr::kable(session_pkgs, booktabs = TRUE)
```

</details>

<br> <br> <br> <br> <br> <br>

::: {.tocify-extend-page data-unique="tocify-extend-page" style="height: 0;"}
:::




